(define (problem p1)
	(:domain bagend)
	(:objects
		zielony czerwony pomaranczowy rozowy niebieski - color
		za rb pc nc zd cd ne ze nf1 nf2 zh ch pi ni - ball
		A B C D E F G H I - room
		k1 k2 k3 k4 k5 k6 k7 k8 - block
		f1 f2 f3 f4 f5 f6 f7 f8 f9 - field
	)
	(:init
		(przejscie A B pomaranczowy)
		(przejscie A C czerwony)
		(przejscie C A czerwony)
		(przejscie B D pomaranczowy)
		(przejscie C E zielony)
		(przejscie E C zielony)
		(przejscie D F zielony)
		(przejscie F D zielony)
		(przejscie E F niebieski)
		(przejscie F E niebieski)
		(przejscie F G rozowy)
		(przejscie F I niebieski)
		(przejscie I F niebieski)
		(przejscie E H czerwony)
		(przejscie H E czerwony)
		(przejscie H I niebieski)
		(przejscie I H niebieski)
		(kolor-kuli za zielony)
		(kolor-kuli rb rozowy)
		(kolor-kuli pc pomaranczowy)
		(kolor-kuli nc niebieski)
		(kolor-kuli zd zielony)
		(kolor-kuli cd czerwony)
		(kolor-kuli ne niebieski)
		(kolor-kuli ze zielony)
		(kolor-kuli nf1 niebieski)
		(kolor-kuli nf2 niebieski)
		(kolor-kuli zh zielony)
		(kolor-kuli ch czerwony)
		(kolor-kuli pi pomaranczowy)
		(kolor-kuli ni niebieski)
		(kula-w za A)
		(kula-w rb B)
		(kula-w pc C)
		(kula-w nc C)
		(kula-w zd D)
		(kula-w cd D)
		(kula-w ne E)
		(kula-w ze E)
		(kula-w nf1 F)
		(kula-w nf2 F)
		(kula-w zh H)
		(kula-w ch H)
		(kula-w pi I)
		(kula-w ni I)
		(merry-w F)
		(blokada-w A)
		
		(obok f1 f2)
		(obok f2 f3)
		(obok f4 f5)
		(obok f5 f6)
		(obok f7 f8)
		(obok f8 f9)
		(obok f1 f4)
		(obok f4 f7)
		(obok f2 f5)
		(obok f5 f8)
		(obok f3 f6)
		(obok f6 f9)
		(klocek-na k5 f1)
		(klocek-na k4 f2)
		(klocek-na k1 f3)
		(klocek-na k8 f4)
		(klocek-na null f5)
		(klocek-na k3 f6)
		(klocek-na k7 f7)
		(klocek-na k2 f8)
		(klocek-na k6 f9)
	)
	(:goal
		(and
			(merry-w G)
			(klocek-na k1 f1)
			(klocek-na k2 f2)
			(klocek-na k3 f3)
			(klocek-na k4 f4)
			(klocek-na k5 f5)
			(klocek-na k6 f6)
			(klocek-na k7 f7)
			(klocek-na k8 f8)
			(klocek-na null f9)
		)
	)
)